type = "added"
message = "Index rotation strategy combining functions of size-based and time-based."

issues = ["graylog-plugin-enterprise#4447"]
pulls = ["14424", "graylog-plugin-enterprise#4572"]

details.user = """
The new index rotation strategy aims to make it easier to achieve good resource usage,
i.e. shards that are neither too small nor too big, while avoiding excessive number
of shards. This has been difficult to date, especially when faced with variable ingest
rate.
"""

details.ops = """
The default settings are based on ES/OS sharding recommendations and generally
do not need to be changed.
The following configuration file settings are available, if you need to modify the behavior
for your requirements:
`time_size_optimizing_rotation_min_size`: index should be at least this big before rotating.
`time_size_optimizing_rotation_max_size`: rotate if index exceeds this limit.
"""
